package federation

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"

	"orion-auth-backend/audit"
	"orion-auth-backend/middleware"
	"orion-auth-backend/pkg"
)

type Handler struct {
	service      *Service
	auditService *audit.Service
}

func NewHandler(service *Service) *Handler {
	return &Handler{service: service}
}

func (h *Handler) SetAuditService(s *audit.Service) {
	h.auditService = s
}

// RegisterPublicRoutes registers federation endpoints that don't require auth.
func (h *Handler) RegisterPublicRoutes(public *gin.RouterGroup) {
	public.GET("/auth/federation/:provider", h.InitSocialLogin)
	public.GET("/auth/federation/:provider/callback", h.Callback)
	public.POST("/auth/federation/confirm-link", h.ConfirmLink)
}

// RegisterAuthenticatedRoutes registers endpoints that require auth.
//
//	readPerm      — account:read_profile (List)
//	managePerm    — account:manage_linked_accounts (Unlink)
//	requireReauth — step-up on Unlink
func (h *Handler) RegisterAuthenticatedRoutes(authenticated *gin.RouterGroup, readPerm, managePerm, requireReauth gin.HandlerFunc) {
	read := authenticated.Group("")
	if readPerm != nil {
		read.Use(readPerm)
	}
	read.GET("/me/linked-accounts", h.ListLinkedAccounts)

	manage := authenticated.Group("")
	if managePerm != nil {
		manage.Use(managePerm)
	}
	if requireReauth != nil {
		manage.Use(requireReauth)
	}
	manage.DELETE("/me/linked-accounts/:id", h.UnlinkAccount)
}

// RegisterAdminRoutes registers admin CRUD for federation providers.
func (h *Handler) RegisterAdminRoutes(admin *gin.RouterGroup) {
	admin.POST("/federation", h.CreateProvider)
	admin.GET("/federation", h.ListProviders)
	admin.PATCH("/federation/:id", h.UpdateProvider)
	admin.DELETE("/federation/:id", h.DeleteProvider)
}

// InitSocialLogin godoc
// @Summary      Initiate social login via a federation provider
// @Tags         Federation
// @Param        provider          path  string true  "Provider name"
// @Param        return_to         query string false "Absolute URL to redirect to after success"
// @Param        oauth_request_id  query string false "Continuation: in-progress OrionAuth authorize request ID"
// @Param        invitation_token  query string false "Pre-bind a social signup to an invitation"
// @Success      302
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Router       /api/v1/auth/federation/{provider} [get]
func (h *Handler) InitSocialLogin(c *gin.Context) {
	providerName := c.Param("provider")

	opts := InitOptions{
		ReturnTo:        c.Query("return_to"),
		InvitationToken: c.Query("invitation_token"),
		IPAddress:       c.ClientIP(),
		UserAgent:       c.Request.UserAgent(),
	}
	if raw := c.Query("oauth_request_id"); raw != "" {
		id, err := uuid.Parse(raw)
		if err != nil {
			pkg.HandleError(c, pkg.ErrBadRequest("oauth_request_id must be a UUID"))
			return
		}
		opts.OAuthRequestID = &id
	}

	authURL, err := h.service.InitSocialLogin(c.Request.Context(), providerName, opts)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	c.Redirect(http.StatusFound, authURL)
}

// Callback godoc
// @Summary      Handle federation provider callback
// @Tags         Federation
// @Produce      json
// @Param        provider path  string true  "Provider name"
// @Param        code     query string true  "Authorization code from provider"
// @Param        state    query string true  "State previously generated by InitSocialLogin"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Router       /api/v1/auth/federation/{provider}/callback [get]
func (h *Handler) Callback(c *gin.Context) {
	providerName := c.Param("provider")
	code := c.Query("code")
	state := c.Query("state")

	if providerErr := c.Query("error"); providerErr != "" {
		desc := c.Query("error_description")
		pkg.HandleError(c, pkg.ErrBadRequest("provider returned error: "+providerErr+" "+desc))
		return
	}

	cbCtx, err := h.service.ProcessCallback(c.Request.Context(), providerName, code, state)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	// Phase 6/7 will replace this with provisioning + session creation +
	// continuation. For now expose the validated claims so the flow is
	// end-to-end testable.
	pkg.OK(c, gin.H{
		"provider":         cbCtx.Provider.Name,
		"external_id":      cbCtx.Claims.ExternalID,
		"email":            cbCtx.Claims.Email,
		"email_verified":   cbCtx.Claims.EmailVerified,
		"name":             cbCtx.Claims.Name,
		"picture":          cbCtx.Claims.Picture,
		"oauth_request_id": cbCtx.AuthRequest.OAuthRequestID,
		"return_to":        cbCtx.AuthRequest.ReturnTo,
	})
}

// ConfirmLinkInput is the body of POST /api/v1/auth/federation/confirm-link.
type ConfirmLinkInput struct {
	Token    string `json:"token" binding:"required"`
	Password string `json:"password" binding:"required"`
}

// ConfirmLink godoc
// @Summary  Confirm a federation account link by supplying the local password
// @Tags     Federation
// @Accept   json
// @Produce  json
// @Param    body body federation.ConfirmLinkInput true "Pending link token + local password"
// @Success  200 {object} map[string]any
// @Failure  400 {object} map[string]any
// @Failure  401 {object} map[string]any
// @Router   /api/v1/auth/federation/confirm-link [post]
func (h *Handler) ConfirmLink(c *gin.Context) {
	var input ConfirmLinkInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	result, err := h.service.ConfirmLink(input.Token, input.Password)
	if err != nil {
		if IsInvalidConfirmPassword(err) {
			if h.auditService != nil {
				h.auditService.LogFromContext(c, audit.ActionFederationLinkConfirmFail, nil)
			}
			pkg.HandleError(c, pkg.ErrUnauthorized("invalid password"))
			return
		}
		pkg.HandleError(c, err)
		return
	}
	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationAccountLinked, map[string]any{
			"user_id": result.User.ID,
		})
	}
	// Phase 7 will attach session creation + continuation redirect. For now
	// the endpoint just confirms the link.
	pkg.OK(c, gin.H{
		"user_id":          result.User.ID,
		"oauth_request_id": result.OAuthRequestID,
		"return_to":        result.ReturnTo,
	})
}

// ListLinkedAccounts godoc
// @Summary      List linked federation accounts for the current user
// @Tags         Federation
// @Produce      json
// @Success      200 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts [get]
func (h *Handler) ListLinkedAccounts(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}

	links, err := h.service.GetLinkedAccounts(userID)
	if err != nil {
		pkg.HandleError(c, pkg.ErrInternal("failed to list linked accounts"))
		return
	}

	pkg.List(c, links, len(links))
}

// UnlinkAccount godoc
// @Summary      Unlink a federation account
// @Tags         Federation
// @Produce      json
// @Param        id path string true "Linked account ID"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts/{id} [delete]
func (h *Handler) UnlinkAccount(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}

	linkID, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid link ID"))
		return
	}

	if err := h.service.UnlinkAccount(linkID, userID); err != nil {
		pkg.HandleError(c, err)
		return
	}

	pkg.OK(c, gin.H{"message": "account unlinked"})
}

// --- Admin ---

// CreateProvider godoc
// @Summary      Create a federation provider
// @Tags         Admin - Federation
// @Accept       json
// @Produce      json
// @Param        body body federation.CreateProviderInput true "Provider creation payload"
// @Success      201 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation [post]
func (h *Handler) CreateProvider(c *gin.Context) {
	var input CreateProviderInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	p, err := h.service.CreateProvider(input)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderCreated, map[string]any{
			"provider_id":   p.ID,
			"provider_name": p.Name,
		})
	}

	pkg.Created(c, gin.H{"provider": p})
}

// ListProviders godoc
// @Summary      List all federation providers
// @Tags         Admin - Federation
// @Produce      json
// @Success      200 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation [get]
func (h *Handler) ListProviders(c *gin.Context) {
	providers, err := h.service.ListProviders()
	if err != nil {
		pkg.HandleError(c, pkg.ErrInternal("failed to list providers"))
		return
	}
	pkg.List(c, providers, len(providers))
}

// UpdateProvider godoc
// @Summary      Update a federation provider
// @Tags         Admin - Federation
// @Accept       json
// @Produce      json
// @Param        id path string true "Provider ID"
// @Param        body body federation.UpdateProviderInput true "Provider update payload"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [patch]
func (h *Handler) UpdateProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	var input UpdateProviderInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	p, err := h.service.UpdateProvider(id, input)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderUpdated, map[string]any{
			"provider_id": id,
		})
	}

	pkg.OK(c, gin.H{"provider": p})
}

// DeleteProvider godoc
// @Summary      Delete a federation provider
// @Tags         Admin - Federation
// @Produce      json
// @Param        id path string true "Provider ID"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [delete]
func (h *Handler) DeleteProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	if err := h.service.DeleteProvider(id); err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderDeleted, map[string]any{
			"provider_id": id,
		})
	}

	pkg.OK(c, gin.H{"message": "provider deleted"})
}
