package federation

import (
	"log/slog"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"

	"orion-auth-backend/audit"
	"orion-auth-backend/middleware"
	"orion-auth-backend/model"
	"orion-auth-backend/pkg"
)

type Handler struct {
	service      *Service
	auditService *audit.Service
}

func NewHandler(service *Service) *Handler {
	return &Handler{service: service}
}

func (h *Handler) SetAuditService(s *audit.Service) {
	h.auditService = s
}

// RegisterPublicRoutes registers federation endpoints that don't require auth.
func (h *Handler) RegisterPublicRoutes(public *gin.RouterGroup) {
	public.GET("/auth/federation/:provider", h.InitSocialLogin)
	public.GET("/auth/federation/:provider/callback", h.Callback)
	public.POST("/auth/federation/confirm-link", h.ConfirmLink)
	public.GET("/auth/federation/pending-signup", h.PeekPendingSignup)
	public.POST("/auth/federation/complete-signup", h.CompleteSignup)
}

// RegisterAuthenticatedRoutes registers endpoints that require auth.
//
//	readPerm      — account:read_profile (List, Get)
//	managePerm    — account:manage_linked_accounts (BeginLink, Unlink)
//	requireReauth — step-up on BeginLink + Unlink
func (h *Handler) RegisterAuthenticatedRoutes(authenticated *gin.RouterGroup, readPerm, managePerm, requireReauth gin.HandlerFunc) {
	read := authenticated.Group("")
	if readPerm != nil {
		read.Use(readPerm)
	}
	read.GET("/me/linked-accounts", h.ListLinkedAccounts)
	read.GET("/me/linked-accounts/:id", h.GetLinkedAccount)

	manage := authenticated.Group("")
	if managePerm != nil {
		manage.Use(managePerm)
	}
	if requireReauth != nil {
		manage.Use(requireReauth)
	}
	manage.POST("/me/linked-accounts/:provider/begin-link", h.BeginLinkAccount)
	manage.DELETE("/me/linked-accounts/:id", h.UnlinkAccount)
}

// RegisterAdminRoutes registers admin CRUD for federation providers.
func (h *Handler) RegisterAdminRoutes(admin *gin.RouterGroup) {
	admin.POST("/federation", h.CreateProvider)
	admin.GET("/federation", h.ListProviders)
	admin.GET("/federation/:id", h.GetProvider)
	admin.PATCH("/federation/:id", h.UpdateProvider)
	admin.DELETE("/federation/:id", h.DeleteProvider)
}

// InitSocialLogin godoc
// @Summary      Initiate social login via a federation provider
// @Tags         Federation
// @Param        provider          path  string true  "Provider name"
// @Param        return_to         query string false "Absolute URL to redirect to after success"
// @Param        oauth_request_id  query string false "Continuation: in-progress OrionAuth authorize request ID"
// @Param        invitation_token  query string false "Pre-bind a social signup to an invitation"
// @Success      302
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Router       /api/v1/auth/federation/{provider} [get]
func (h *Handler) InitSocialLogin(c *gin.Context) {
	providerName := c.Param("provider")

	opts := InitOptions{
		ReturnTo:        c.Query("return_to"),
		InvitationToken: c.Query("invitation_token"),
		IPAddress:       c.ClientIP(),
		UserAgent:       c.Request.UserAgent(),
	}
	if raw := c.Query("oauth_request_id"); raw != "" {
		id, err := uuid.Parse(raw)
		if err != nil {
			pkg.HandleError(c, pkg.ErrBadRequest("oauth_request_id must be a UUID"))
			return
		}
		opts.OAuthRequestID = &id
	}

	authURL, err := h.service.InitSocialLogin(c.Request.Context(), providerName, opts)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	c.Redirect(http.StatusFound, authURL)
}

// Callback godoc
// @Summary      Handle federation provider callback
// @Tags         Federation
// @Param        provider path  string true  "Provider name"
// @Param        code     query string true  "Authorization code from provider"
// @Param        state    query string true  "State previously generated by InitSocialLogin"
// @Success      302
// @Failure      400 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Router       /api/v1/auth/federation/{provider}/callback [get]
func (h *Handler) Callback(c *gin.Context) {
	providerName := c.Param("provider")
	code := c.Query("code")
	state := c.Query("state")

	if providerErr := c.Query("error"); providerErr != "" {
		h.redirectLoginError(c, providerErr)
		return
	}

	cbCtx, err := h.service.ProcessCallback(c.Request.Context(), providerName, code, state)
	if err != nil {
		slog.Warn("federation callback failed", "provider", providerName, "error", err)
		h.recordLoginFailure(c, providerName, err)
		h.redirectLoginError(c, "callback_failed")
		return
	}

	outcome, err := h.service.FindOrProvisionUser(cbCtx)
	if err != nil {
		h.recordLoginFailure(c, providerName, err)
		// Authenticated link errors land back on the AuthUI's linked-accounts
		// screen with a precise status so the SPA can show a usable message.
		if cbCtx.AuthRequest.LinkUserID != nil {
			h.redirectLinkResult(c, cbCtx.AuthRequest, providerName, linkResultFromErr(err))
			return
		}
		switch {
		case err == ErrAccountExistsLinkRequired:
			h.redirectLoginError(c, "account_exists_link_required")
		case err == ErrRegistrationDisabled:
			h.redirectLoginError(c, "registration_disabled")
		default:
			h.redirectLoginError(c, "provisioning_failed")
		}
		return
	}

	switch outcome.Kind {
	case ProvisionAuthenticatedLink:
		if h.auditService != nil {
			h.auditService.LogFromContext(c, audit.ActionFederationAccountLinked, map[string]any{
				"user_id":     outcome.User.ID,
				"provider":    providerName,
				"link_id":     outcome.Link.ID,
				"external_id": outcome.Link.ExternalID,
			})
		}
		h.redirectLinkResult(c, cbCtx.AuthRequest, providerName, "linked")
		return
	case ProvisionPendingLinkConfirmation:
		c.Redirect(http.StatusFound, h.service.AuthUIBaseURL()+"/link-account?token="+url.QueryEscape(outcome.PendingLinkToken))
		return
	case ProvisionPendingSignup:
		c.Redirect(http.StatusFound, h.service.AuthUIBaseURL()+"/complete-account?token="+url.QueryEscape(outcome.PendingSignupToken))
		return
	case ProvisionLoginExisting:
		if h.auditService != nil {
			h.auditService.LogFromContext(c, audit.ActionFederationLoginSucceeded, map[string]any{
				"user_id":  outcome.User.ID,
				"provider": providerName,
			})
		}
		h.continueAfterLogin(c, providerName, outcome.User, cbCtx.AuthRequest)
	}
}

// linkResultFromErr maps service errors raised during an authenticated link
// flow to compact status codes that the AuthUI can interpret without
// re-parsing prose. Anything unknown maps to "link_failed".
func linkResultFromErr(err error) string {
	if err == ErrIdentityLinkedToOtherUser {
		return "identity_already_linked"
	}
	return "link_failed"
}

// redirectLinkResult sends the user back to either the SPA that
// originated the link flow (when authReq.ReturnTo matches the AuthUI
// origin or any extra trusted origin) or, as fallback, the AuthUI's
// /linked-accounts screen. The status (linked / identity_already_linked
// / link_failed) and provider name are appended as query params.
func (h *Handler) redirectLinkResult(c *gin.Context, authReq *model.FederationAuthRequest, providerName, status string) {
	authUI := h.service.AuthUIBaseURL()
	target := authUI + "/linked-accounts"
	if authReq.ReturnTo != nil {
		bases := append([]string{authUI}, h.service.AllowedReturnToOrigins()...)
		if safeReturnTo(*authReq.ReturnTo, bases...) {
			target = *authReq.ReturnTo
		}
	}
	sep := "?"
	if strings.Contains(target, "?") {
		sep = "&"
	}
	c.Redirect(http.StatusFound, target+sep+"link_status="+url.QueryEscape(status)+"&provider="+url.QueryEscape(providerName))
}

// continueAfterLogin runs the post-provisioning redirect logic shared
// between Callback and ConfirmLink. When the federation flow was started
// inside an OrionAuth /authorize (oauth_request_id present), the OAuth
// dance is resumed in place and the user is redirected to the original
// client's redirect_uri with the code+state. Otherwise the user is sent
// to authReq.ReturnTo (within the AuthUI origin) or to the AuthUI home.
func (h *Handler) continueAfterLogin(c *gin.Context, providerName string, u *model.User, authReq *model.FederationAuthRequest) {
	resumer := h.service.OAuthResumerClient()
	authUI := h.service.AuthUIBaseURL()

	// Standalone social login (no OAuth in flight): go to return_to or home.
	// Onboarding (must_set_password) is left to the downstream client to
	// detect via /me — a backend-driven onboarding redirect would need its
	// own short-lived token because the AuthUI has no bearer to call
	// /me/set-password at this point. Tracked as a follow-up.
	if authReq.OAuthRequestID == nil || resumer == nil {
		target := authUI + "/"
		if authReq.ReturnTo != nil && safeReturnTo(*authReq.ReturnTo, authUI) {
			target = *authReq.ReturnTo
		}
		c.Redirect(http.StatusFound, target)
		return
	}

	status, err := resumer.ResumeAuthorizeAfterExternalLogin(
		*authReq.OAuthRequestID, u.ID, providerName, c.ClientIP(), c.Request.UserAgent(),
	)
	if err != nil {
		h.redirectLoginError(c, "authorize_resume_failed")
		return
	}

	if status.RequiresMFA {
		c.Redirect(http.StatusFound, authUI+"/mfa?request_id="+status.RequestID.String())
		return
	}
	if status.RequiresConsent {
		c.Redirect(http.StatusFound, authUI+"/consent?request_id="+status.RequestID.String())
		return
	}

	completion, err := resumer.CompleteAuthorizeFirstParty(status.RequestID, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		h.redirectLoginError(c, "authorize_complete_failed")
		return
	}
	c.Redirect(http.StatusFound, completion.RedirectURL)
}

func (h *Handler) redirectLoginError(c *gin.Context, code string) {
	c.Redirect(http.StatusFound, h.service.AuthUIBaseURL()+"/login?error="+url.QueryEscape(code))
}

func (h *Handler) recordLoginFailure(c *gin.Context, providerName string, err error) {
	if h.auditService == nil {
		return
	}
	h.auditService.LogFromContext(c, audit.ActionFederationLoginFailed, map[string]any{
		"provider": providerName,
		"error":    err.Error(),
	})
}

// safeReturnTo enforces a minimal allowlist: the target's scheme+host
// must match one of the allowed bases. Empty/unparsable bases are
// skipped silently so callers can pass an optional AuthUI base plus
// an arbitrary list of trusted SPA origins without pre-filtering.
func safeReturnTo(target string, allowedBases ...string) bool {
	if target == "" {
		return false
	}
	t, err := url.Parse(target)
	if err != nil {
		return false
	}
	for _, raw := range allowedBases {
		if raw == "" {
			continue
		}
		base, err := url.Parse(raw)
		if err != nil {
			continue
		}
		if strings.EqualFold(t.Scheme, base.Scheme) && strings.EqualFold(t.Host, base.Host) {
			return true
		}
	}
	return false
}

// ConfirmLinkInput is the body of POST /api/v1/auth/federation/confirm-link.
type ConfirmLinkInput struct {
	Token    string `json:"token" binding:"required"`
	Password string `json:"password" binding:"required"`
}

// ConfirmLink godoc
// @Summary  Confirm a federation account link by supplying the local password
// @Tags     Federation
// @Accept   json
// @Produce  json
// @Param    body body federation.ConfirmLinkInput true "Pending link token + local password"
// @Success  200 {object} map[string]any
// @Failure  400 {object} map[string]any
// @Failure  401 {object} map[string]any
// @Router   /api/v1/auth/federation/confirm-link [post]
func (h *Handler) ConfirmLink(c *gin.Context) {
	var input ConfirmLinkInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	result, err := h.service.ConfirmLink(input.Token, input.Password)
	if err != nil {
		if IsInvalidConfirmPassword(err) {
			if h.auditService != nil {
				h.auditService.LogFromContext(c, audit.ActionFederationLinkConfirmFail, nil)
			}
			pkg.HandleError(c, pkg.ErrUnauthorized("invalid password"))
			return
		}
		pkg.HandleError(c, err)
		return
	}
	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationAccountLinked, map[string]any{
			"user_id": result.User.ID,
		})
	}

	// Reconstitute a minimal auth request to drive the shared continuation
	// helper. The pending link carried the original return_to and
	// oauth_request_id forward from the auth-request row.
	stub := &model.FederationAuthRequest{
		OAuthRequestID: result.OAuthRequestID,
		ReturnTo:       result.ReturnTo,
	}
	// Best-effort: name the federation provider for the resumed authorize
	// AuthMethods log. ConfirmLink created exactly one new link for this
	// user, so any of their links surfaces the right provider.
	providerName := "federation"
	if links, _ := h.service.repo.FindLinksByUser(result.User.ID); len(links) > 0 {
		if prov, _ := h.service.repo.FindProviderByID(links[0].ProviderID); prov != nil {
			providerName = prov.Name
		}
	}

	// Successful confirmation responds with a JSON payload carrying the
	// final redirect URL so the AuthUI can navigate the browser without a
	// second round-trip. The AuthUI is expected to honour `redirect`.
	target := h.computeContinuationURL(c, providerName, result.User, stub)
	pkg.OK(c, gin.H{
		"user_id":  result.User.ID,
		"redirect": target,
	})
}

// computeContinuationURL mirrors continueAfterLogin but returns the URL as
// a string (for ConfirmLink which answers JSON, letting the SPA do the
// in-page navigation rather than a hard browser redirect).
func (h *Handler) computeContinuationURL(c *gin.Context, providerName string, u *model.User, authReq *model.FederationAuthRequest) string {
	resumer := h.service.OAuthResumerClient()
	authUI := h.service.AuthUIBaseURL()

	if authReq.OAuthRequestID == nil || resumer == nil {
		target := authUI + "/"
		if authReq.ReturnTo != nil && safeReturnTo(*authReq.ReturnTo, authUI) {
			target = *authReq.ReturnTo
		}
		return target
	}
	status, err := resumer.ResumeAuthorizeAfterExternalLogin(*authReq.OAuthRequestID, u.ID, providerName, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		return authUI + "/login?error=authorize_resume_failed"
	}
	if status.RequiresMFA {
		return authUI + "/mfa?request_id=" + status.RequestID.String()
	}
	if status.RequiresConsent {
		return authUI + "/consent?request_id=" + status.RequestID.String()
	}
	completion, err := resumer.CompleteAuthorizeFirstParty(status.RequestID, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		return authUI + "/login?error=authorize_complete_failed"
	}
	return completion.RedirectURL
}

// PeekPendingSignup godoc
// @Summary  Read-only view of a pending federation signup
// @Tags     Federation
// @Produce  json
// @Param    token query string true "Pending signup token from /complete-account redirect"
// @Success  200 {object} map[string]any
// @Failure  400 {object} map[string]any
// @Router   /api/v1/auth/federation/pending-signup [get]
func (h *Handler) PeekPendingSignup(c *gin.Context) {
	view, err := h.service.PeekPendingSignup(c.Query("token"))
	if err != nil {
		pkg.HandleError(c, err)
		return
	}
	pkg.OK(c, gin.H{
		"provider_name":         view.ProviderName,
		"provider_display_name": view.ProviderDisplayName,
		"email":                 view.Email,
		"email_verified":        view.EmailVerified,
		"display_name":          view.DisplayName,
		"expires_at":            view.ExpiresAt,
	})
}

// CompleteSignupHTTPInput is the body of POST /api/v1/auth/federation/complete-signup.
type CompleteSignupHTTPInput struct {
	Token       string         `json:"token" binding:"required"`
	Password    string         `json:"password" binding:"required"`
	DisplayName string         `json:"display_name"`
	ExtraFields map[string]any `json:"extra_fields,omitempty"`
}

// CompleteSignup godoc
// @Summary  Finalise a federation signup by setting the local password
// @Tags     Federation
// @Accept   json
// @Produce  json
// @Param    body body federation.CompleteSignupHTTPInput true "Pending signup token + chosen password"
// @Success  200 {object} map[string]any
// @Failure  400 {object} map[string]any
// @Router   /api/v1/auth/federation/complete-signup [post]
func (h *Handler) CompleteSignup(c *gin.Context) {
	var input CompleteSignupHTTPInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	result, err := h.service.CompleteSignup(CompleteSignupInput{
		Token:       input.Token,
		Password:    input.Password,
		DisplayName: input.DisplayName,
		ExtraFields: input.ExtraFields,
	})
	if err != nil {
		pkg.HandleError(c, err)
		return
	}
	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationUserProvisioned, map[string]any{
			"user_id": result.User.ID,
		})
	}

	// Best-effort provider name lookup for the resumed authorize log.
	providerName := "federation"
	if links, _ := h.service.repo.FindLinksByUser(result.User.ID); len(links) > 0 {
		if prov, _ := h.service.repo.FindProviderByID(links[0].ProviderID); prov != nil {
			providerName = prov.Name
		}
	}
	stub := &model.FederationAuthRequest{
		OAuthRequestID: result.OAuthRequestID,
		ReturnTo:       result.ReturnTo,
	}
	pkg.OK(c, gin.H{
		"user_id":  result.User.ID,
		"redirect": h.computeContinuationURL(c, providerName, result.User, stub),
	})
}

// linkedAccountResponse enriches a FederationLink with the slug of its
// provider so SDK consumers can merge the list against /auth/settings
// without an extra round-trip. ProviderName is empty if the relationship
// was not preloaded (defensive — repository methods always preload).
type linkedAccountResponse struct {
	*model.FederationLink
	ProviderName string `json:"provider_name"`
}

func toLinkedAccountResponse(link *model.FederationLink) linkedAccountResponse {
	r := linkedAccountResponse{FederationLink: link}
	if link.Provider != nil {
		r.ProviderName = link.Provider.Name
	}
	return r
}

// ListLinkedAccounts godoc
// @Summary      List linked federation accounts for the current user
// @Tags         Federation
// @Produce      json
// @Success      200 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts [get]
func (h *Handler) ListLinkedAccounts(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}

	links, err := h.service.GetLinkedAccounts(userID)
	if err != nil {
		pkg.HandleError(c, pkg.ErrInternal("failed to list linked accounts"))
		return
	}

	out := make([]linkedAccountResponse, len(links))
	for i := range links {
		out[i] = toLinkedAccountResponse(&links[i])
	}
	pkg.List(c, out, len(out))
}

// GetLinkedAccount godoc
// @Summary      Get a single linked federation account
// @Tags         Federation
// @Produce      json
// @Param        id path string true "Linked account ID"
// @Success      200 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts/{id} [get]
func (h *Handler) GetLinkedAccount(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}
	linkID, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid link ID"))
		return
	}
	link, err := h.service.GetLinkedAccount(linkID, userID)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}
	pkg.OK(c, gin.H{"link": toLinkedAccountResponse(link)})
}

// BeginLinkAccountInput is the body of POST /api/v1/me/linked-accounts/{provider}/begin-link.
type BeginLinkAccountInput struct {
	// ReturnTo is the URL the AuthUI wants the user to land on after the
	// provider callback completes (must be same-origin with the AuthUI base).
	// Defaults to AuthUI /linked-accounts when empty.
	ReturnTo string `json:"return_to,omitempty"`
}

// BeginLinkAccount godoc
// @Summary      Start linking a federation account to the current user
// @Tags         Federation
// @Accept       json
// @Produce      json
// @Param        provider path string                                 true  "Provider name"
// @Param        body     body federation.BeginLinkAccountInput       false "Optional return_to"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Failure      403 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts/{provider}/begin-link [post]
func (h *Handler) BeginLinkAccount(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}
	providerName := c.Param("provider")
	if providerName == "" {
		pkg.HandleError(c, pkg.ErrBadRequest("provider is required"))
		return
	}

	// Body is optional — SPAs without a return_to can POST an empty body.
	var input BeginLinkAccountInput
	if c.Request.ContentLength > 0 {
		if err := c.ShouldBindJSON(&input); err != nil {
			pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
			return
		}
	}

	redirect, err := h.service.BeginLink(c.Request.Context(), userID, providerName, InitOptions{
		ReturnTo:  input.ReturnTo,
		IPAddress: c.ClientIP(),
		UserAgent: c.Request.UserAgent(),
	})
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationLoginSucceeded, map[string]any{
			"action":   "begin_link",
			"user_id":  userID,
			"provider": providerName,
		})
	}

	pkg.OK(c, gin.H{"redirect_url": redirect, "provider": providerName})
}

// UnlinkAccount godoc
// @Summary      Unlink a federation account
// @Tags         Federation
// @Produce      json
// @Param        id path string true "Linked account ID"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts/{id} [delete]
func (h *Handler) UnlinkAccount(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}

	linkID, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid link ID"))
		return
	}

	if err := h.service.UnlinkAccount(linkID, userID); err != nil {
		pkg.HandleError(c, err)
		return
	}

	pkg.OK(c, gin.H{"message": "account unlinked"})
}

// --- Admin ---

// CreateProvider godoc
// @Summary      Create a federation provider
// @Tags         Admin - Federation
// @Accept       json
// @Produce      json
// @Param        body body federation.CreateProviderInput true "Provider creation payload"
// @Success      201 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation [post]
func (h *Handler) CreateProvider(c *gin.Context) {
	var input CreateProviderInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	p, err := h.service.CreateProvider(input)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderCreated, map[string]any{
			"provider_id":   p.ID,
			"provider_name": p.Name,
		})
	}

	pkg.Created(c, gin.H{"provider": p})
}

// GetProvider godoc
// @Summary      Get a single federation provider
// @Tags         Admin - Federation
// @Produce      json
// @Param        id path string true "Provider ID"
// @Success      200 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [get]
func (h *Handler) GetProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	p, err := h.service.GetProvider(id)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}
	pkg.OK(c, gin.H{"provider": p})
}

// ListProviders godoc
// @Summary      List all federation providers
// @Tags         Admin - Federation
// @Produce      json
// @Success      200 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation [get]
func (h *Handler) ListProviders(c *gin.Context) {
	providers, err := h.service.ListProviders()
	if err != nil {
		pkg.HandleError(c, pkg.ErrInternal("failed to list providers"))
		return
	}
	pkg.List(c, providers, len(providers))
}

// UpdateProvider godoc
// @Summary      Update a federation provider
// @Tags         Admin - Federation
// @Accept       json
// @Produce      json
// @Param        id path string true "Provider ID"
// @Param        body body federation.UpdateProviderInput true "Provider update payload"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [patch]
func (h *Handler) UpdateProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	var input UpdateProviderInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	p, err := h.service.UpdateProvider(id, input)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	// Compose an audit diff that captures which configuration knobs the
	// admin touched. ClientSecret presence is recorded but its value is
	// never logged.
	changed := map[string]any{"provider_id": id}
	if input.ClientID != nil {
		changed["client_id"] = *input.ClientID
	}
	if input.ClientSecret != nil {
		changed["client_secret_rotated"] = true
	}
	if input.IssuerURL != nil {
		changed["issuer_url"] = *input.IssuerURL
	}
	if input.JWKSUri != nil {
		changed["jwks_uri"] = *input.JWKSUri
	}
	if input.SyncOnLogin != nil {
		changed["sync_on_login"] = *input.SyncOnLogin
	}
	if input.AllowLinkConfirmation != nil {
		changed["allow_link_confirmation"] = *input.AllowLinkConfirmation
	}
	if len(input.AttributeMapper) > 0 {
		changed["attribute_mapper_changed"] = true
	}
	if input.Active != nil {
		changed["active"] = *input.Active
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderUpdated, changed)
	}

	pkg.OK(c, gin.H{"provider": p})
}

// DeleteProvider godoc
// @Summary      Delete a federation provider
// @Tags         Admin - Federation
// @Produce      json
// @Param        id path string true "Provider ID"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [delete]
func (h *Handler) DeleteProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	if err := h.service.DeleteProvider(id); err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderDeleted, map[string]any{
			"provider_id": id,
		})
	}

	pkg.OK(c, gin.H{"message": "provider deleted"})
}
