package federation

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"

	"orion-auth-backend/audit"
	"orion-auth-backend/middleware"
	"orion-auth-backend/model"
	"orion-auth-backend/pkg"
)

type Handler struct {
	service      *Service
	auditService *audit.Service
}

func NewHandler(service *Service) *Handler {
	return &Handler{service: service}
}

func (h *Handler) SetAuditService(s *audit.Service) {
	h.auditService = s
}

// RegisterPublicRoutes registers federation endpoints that don't require auth.
func (h *Handler) RegisterPublicRoutes(public *gin.RouterGroup) {
	public.GET("/auth/federation/:provider", h.InitSocialLogin)
	public.GET("/auth/federation/:provider/callback", h.Callback)
	public.POST("/auth/federation/confirm-link", h.ConfirmLink)
}

// RegisterAuthenticatedRoutes registers endpoints that require auth.
//
//	readPerm      — account:read_profile (List)
//	managePerm    — account:manage_linked_accounts (Unlink)
//	requireReauth — step-up on Unlink
func (h *Handler) RegisterAuthenticatedRoutes(authenticated *gin.RouterGroup, readPerm, managePerm, requireReauth gin.HandlerFunc) {
	read := authenticated.Group("")
	if readPerm != nil {
		read.Use(readPerm)
	}
	read.GET("/me/linked-accounts", h.ListLinkedAccounts)

	manage := authenticated.Group("")
	if managePerm != nil {
		manage.Use(managePerm)
	}
	if requireReauth != nil {
		manage.Use(requireReauth)
	}
	manage.DELETE("/me/linked-accounts/:id", h.UnlinkAccount)
}

// RegisterAdminRoutes registers admin CRUD for federation providers.
func (h *Handler) RegisterAdminRoutes(admin *gin.RouterGroup) {
	admin.POST("/federation", h.CreateProvider)
	admin.GET("/federation", h.ListProviders)
	admin.GET("/federation/:id", h.GetProvider)
	admin.PATCH("/federation/:id", h.UpdateProvider)
	admin.DELETE("/federation/:id", h.DeleteProvider)
}

// InitSocialLogin godoc
// @Summary      Initiate social login via a federation provider
// @Tags         Federation
// @Param        provider          path  string true  "Provider name"
// @Param        return_to         query string false "Absolute URL to redirect to after success"
// @Param        oauth_request_id  query string false "Continuation: in-progress OrionAuth authorize request ID"
// @Param        invitation_token  query string false "Pre-bind a social signup to an invitation"
// @Success      302
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Router       /api/v1/auth/federation/{provider} [get]
func (h *Handler) InitSocialLogin(c *gin.Context) {
	providerName := c.Param("provider")

	opts := InitOptions{
		ReturnTo:        c.Query("return_to"),
		InvitationToken: c.Query("invitation_token"),
		IPAddress:       c.ClientIP(),
		UserAgent:       c.Request.UserAgent(),
	}
	if raw := c.Query("oauth_request_id"); raw != "" {
		id, err := uuid.Parse(raw)
		if err != nil {
			pkg.HandleError(c, pkg.ErrBadRequest("oauth_request_id must be a UUID"))
			return
		}
		opts.OAuthRequestID = &id
	}

	authURL, err := h.service.InitSocialLogin(c.Request.Context(), providerName, opts)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	c.Redirect(http.StatusFound, authURL)
}

// Callback godoc
// @Summary      Handle federation provider callback
// @Tags         Federation
// @Param        provider path  string true  "Provider name"
// @Param        code     query string true  "Authorization code from provider"
// @Param        state    query string true  "State previously generated by InitSocialLogin"
// @Success      302
// @Failure      400 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Router       /api/v1/auth/federation/{provider}/callback [get]
func (h *Handler) Callback(c *gin.Context) {
	providerName := c.Param("provider")
	code := c.Query("code")
	state := c.Query("state")

	if providerErr := c.Query("error"); providerErr != "" {
		h.redirectLoginError(c, providerErr)
		return
	}

	cbCtx, err := h.service.ProcessCallback(c.Request.Context(), providerName, code, state)
	if err != nil {
		h.recordLoginFailure(c, providerName, err)
		h.redirectLoginError(c, "callback_failed")
		return
	}

	outcome, err := h.service.FindOrProvisionUser(cbCtx)
	if err != nil {
		h.recordLoginFailure(c, providerName, err)
		switch {
		case err == ErrAccountExistsLinkRequired:
			h.redirectLoginError(c, "account_exists_link_required")
		case err == ErrRegistrationDisabled:
			h.redirectLoginError(c, "registration_disabled")
		default:
			h.redirectLoginError(c, "provisioning_failed")
		}
		return
	}

	switch outcome.Kind {
	case ProvisionPendingLinkConfirmation:
		c.Redirect(http.StatusFound, h.service.AuthUIBaseURL()+"/link-account?token="+url.QueryEscape(outcome.PendingLinkToken))
		return
	case ProvisionCreated:
		if h.auditService != nil {
			h.auditService.LogFromContext(c, audit.ActionFederationUserProvisioned, map[string]any{
				"user_id":  outcome.User.ID,
				"provider": providerName,
			})
		}
		h.continueAfterLogin(c, providerName, outcome.User, cbCtx.AuthRequest)
	case ProvisionLoginExisting:
		if h.auditService != nil {
			h.auditService.LogFromContext(c, audit.ActionFederationLoginSucceeded, map[string]any{
				"user_id":  outcome.User.ID,
				"provider": providerName,
			})
		}
		h.continueAfterLogin(c, providerName, outcome.User, cbCtx.AuthRequest)
	}
}

// continueAfterLogin runs the post-provisioning redirect logic shared
// between Callback and ConfirmLink. When the federation flow was started
// inside an OrionAuth /authorize (oauth_request_id present), the OAuth
// dance is resumed in place and the user is redirected to the original
// client's redirect_uri with the code+state. Otherwise the user is sent
// to authReq.ReturnTo (within the AuthUI origin) or to the AuthUI home.
func (h *Handler) continueAfterLogin(c *gin.Context, providerName string, u *model.User, authReq *model.FederationAuthRequest) {
	resumer := h.service.OAuthResumerClient()
	authUI := h.service.AuthUIBaseURL()

	onboardingSuffix := ""
	if u.MustSetPassword {
		onboardingSuffix = "?onboarding=set_password"
	}

	// Standalone social login (no OAuth in flight): go to return_to or home.
	if authReq.OAuthRequestID == nil || resumer == nil {
		target := authUI + "/" + onboardingSuffix
		if authReq.ReturnTo != nil && safeReturnTo(*authReq.ReturnTo, authUI) {
			target = *authReq.ReturnTo
		}
		c.Redirect(http.StatusFound, target)
		return
	}

	status, err := resumer.ResumeAuthorizeAfterExternalLogin(
		*authReq.OAuthRequestID, u.ID, providerName, c.ClientIP(), c.Request.UserAgent(),
	)
	if err != nil {
		h.redirectLoginError(c, "authorize_resume_failed")
		return
	}

	if status.RequiresMFA {
		c.Redirect(http.StatusFound, authUI+"/mfa?request_id="+status.RequestID.String())
		return
	}
	if status.RequiresConsent {
		c.Redirect(http.StatusFound, authUI+"/consent?request_id="+status.RequestID.String())
		return
	}

	completion, err := resumer.CompleteAuthorizeFirstParty(status.RequestID, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		h.redirectLoginError(c, "authorize_complete_failed")
		return
	}
	final := completion.RedirectURL
	if u.MustSetPassword {
		final = authUI + "/complete-account" + onboardingSuffix + "&continue=" + url.QueryEscape(completion.RedirectURL)
	}
	c.Redirect(http.StatusFound, final)
}

func (h *Handler) redirectLoginError(c *gin.Context, code string) {
	c.Redirect(http.StatusFound, h.service.AuthUIBaseURL()+"/login?error="+url.QueryEscape(code))
}

func (h *Handler) recordLoginFailure(c *gin.Context, providerName string, err error) {
	if h.auditService == nil {
		return
	}
	h.auditService.LogFromContext(c, audit.ActionFederationLoginFailed, map[string]any{
		"provider": providerName,
		"error":    err.Error(),
	})
}

// safeReturnTo enforces a minimal allowlist: only same-origin redirects to
// the AuthUI base URL are accepted, so an attacker cannot use the
// federation flow as an open redirect.
func safeReturnTo(target, authUIBase string) bool {
	if target == "" {
		return false
	}
	t, err := url.Parse(target)
	if err != nil {
		return false
	}
	base, err := url.Parse(authUIBase)
	if err != nil {
		return false
	}
	return strings.EqualFold(t.Scheme, base.Scheme) && strings.EqualFold(t.Host, base.Host)
}

// ConfirmLinkInput is the body of POST /api/v1/auth/federation/confirm-link.
type ConfirmLinkInput struct {
	Token    string `json:"token" binding:"required"`
	Password string `json:"password" binding:"required"`
}

// ConfirmLink godoc
// @Summary  Confirm a federation account link by supplying the local password
// @Tags     Federation
// @Accept   json
// @Produce  json
// @Param    body body federation.ConfirmLinkInput true "Pending link token + local password"
// @Success  200 {object} map[string]any
// @Failure  400 {object} map[string]any
// @Failure  401 {object} map[string]any
// @Router   /api/v1/auth/federation/confirm-link [post]
func (h *Handler) ConfirmLink(c *gin.Context) {
	var input ConfirmLinkInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	result, err := h.service.ConfirmLink(input.Token, input.Password)
	if err != nil {
		if IsInvalidConfirmPassword(err) {
			if h.auditService != nil {
				h.auditService.LogFromContext(c, audit.ActionFederationLinkConfirmFail, nil)
			}
			pkg.HandleError(c, pkg.ErrUnauthorized("invalid password"))
			return
		}
		pkg.HandleError(c, err)
		return
	}
	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationAccountLinked, map[string]any{
			"user_id": result.User.ID,
		})
	}

	// Reconstitute a minimal auth request to drive the shared continuation
	// helper. The pending link carried the original return_to and
	// oauth_request_id forward from the auth-request row.
	stub := &model.FederationAuthRequest{
		OAuthRequestID: result.OAuthRequestID,
		ReturnTo:       result.ReturnTo,
	}
	// Best-effort: name the federation provider for the resumed authorize
	// AuthMethods log. ConfirmLink created exactly one new link for this
	// user, so any of their links surfaces the right provider.
	providerName := "federation"
	if links, _ := h.service.repo.FindLinksByUser(result.User.ID); len(links) > 0 {
		if prov, _ := h.service.repo.FindProviderByID(links[0].ProviderID); prov != nil {
			providerName = prov.Name
		}
	}

	// Successful confirmation responds with a JSON payload carrying the
	// final redirect URL so the AuthUI can navigate the browser without a
	// second round-trip. The AuthUI is expected to honour `redirect`.
	target := h.computeContinuationURL(c, providerName, result.User, stub)
	pkg.OK(c, gin.H{
		"user_id":  result.User.ID,
		"redirect": target,
	})
}

// computeContinuationURL mirrors continueAfterLogin but returns the URL as
// a string (for ConfirmLink which answers JSON, letting the SPA do the
// in-page navigation rather than a hard browser redirect).
func (h *Handler) computeContinuationURL(c *gin.Context, providerName string, u *model.User, authReq *model.FederationAuthRequest) string {
	resumer := h.service.OAuthResumerClient()
	authUI := h.service.AuthUIBaseURL()

	onboardingSuffix := ""
	if u.MustSetPassword {
		onboardingSuffix = "?onboarding=set_password"
	}
	if authReq.OAuthRequestID == nil || resumer == nil {
		target := authUI + "/" + onboardingSuffix
		if authReq.ReturnTo != nil && safeReturnTo(*authReq.ReturnTo, authUI) {
			target = *authReq.ReturnTo
		}
		return target
	}
	status, err := resumer.ResumeAuthorizeAfterExternalLogin(*authReq.OAuthRequestID, u.ID, providerName, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		return authUI + "/login?error=authorize_resume_failed"
	}
	if status.RequiresMFA {
		return authUI + "/mfa?request_id=" + status.RequestID.String()
	}
	if status.RequiresConsent {
		return authUI + "/consent?request_id=" + status.RequestID.String()
	}
	completion, err := resumer.CompleteAuthorizeFirstParty(status.RequestID, c.ClientIP(), c.Request.UserAgent())
	if err != nil {
		return authUI + "/login?error=authorize_complete_failed"
	}
	if u.MustSetPassword {
		return authUI + "/complete-account" + onboardingSuffix + "&continue=" + url.QueryEscape(completion.RedirectURL)
	}
	return completion.RedirectURL
}

// ListLinkedAccounts godoc
// @Summary      List linked federation accounts for the current user
// @Tags         Federation
// @Produce      json
// @Success      200 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts [get]
func (h *Handler) ListLinkedAccounts(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}

	links, err := h.service.GetLinkedAccounts(userID)
	if err != nil {
		pkg.HandleError(c, pkg.ErrInternal("failed to list linked accounts"))
		return
	}

	pkg.List(c, links, len(links))
}

// UnlinkAccount godoc
// @Summary      Unlink a federation account
// @Tags         Federation
// @Produce      json
// @Param        id path string true "Linked account ID"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      401 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/me/linked-accounts/{id} [delete]
func (h *Handler) UnlinkAccount(c *gin.Context) {
	userID, ok := middleware.GetUserID(c)
	if !ok {
		pkg.HandleError(c, pkg.ErrUnauthorized("not authenticated"))
		return
	}

	linkID, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid link ID"))
		return
	}

	if err := h.service.UnlinkAccount(linkID, userID); err != nil {
		pkg.HandleError(c, err)
		return
	}

	pkg.OK(c, gin.H{"message": "account unlinked"})
}

// --- Admin ---

// CreateProvider godoc
// @Summary      Create a federation provider
// @Tags         Admin - Federation
// @Accept       json
// @Produce      json
// @Param        body body federation.CreateProviderInput true "Provider creation payload"
// @Success      201 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation [post]
func (h *Handler) CreateProvider(c *gin.Context) {
	var input CreateProviderInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	p, err := h.service.CreateProvider(input)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderCreated, map[string]any{
			"provider_id":   p.ID,
			"provider_name": p.Name,
		})
	}

	pkg.Created(c, gin.H{"provider": p})
}

// GetProvider godoc
// @Summary      Get a single federation provider
// @Tags         Admin - Federation
// @Produce      json
// @Param        id path string true "Provider ID"
// @Success      200 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [get]
func (h *Handler) GetProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	p, err := h.service.GetProvider(id)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}
	pkg.OK(c, gin.H{"provider": p})
}

// ListProviders godoc
// @Summary      List all federation providers
// @Tags         Admin - Federation
// @Produce      json
// @Success      200 {object} map[string]any
// @Failure      500 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation [get]
func (h *Handler) ListProviders(c *gin.Context) {
	providers, err := h.service.ListProviders()
	if err != nil {
		pkg.HandleError(c, pkg.ErrInternal("failed to list providers"))
		return
	}
	pkg.List(c, providers, len(providers))
}

// UpdateProvider godoc
// @Summary      Update a federation provider
// @Tags         Admin - Federation
// @Accept       json
// @Produce      json
// @Param        id path string true "Provider ID"
// @Param        body body federation.UpdateProviderInput true "Provider update payload"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [patch]
func (h *Handler) UpdateProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	var input UpdateProviderInput
	if err := c.ShouldBindJSON(&input); err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid request body: "+err.Error()))
		return
	}
	p, err := h.service.UpdateProvider(id, input)
	if err != nil {
		pkg.HandleError(c, err)
		return
	}

	// Compose an audit diff that captures which configuration knobs the
	// admin touched. ClientSecret presence is recorded but its value is
	// never logged.
	changed := map[string]any{"provider_id": id}
	if input.ClientID != nil {
		changed["client_id"] = *input.ClientID
	}
	if input.ClientSecret != nil {
		changed["client_secret_rotated"] = true
	}
	if input.IssuerURL != nil {
		changed["issuer_url"] = *input.IssuerURL
	}
	if input.JWKSUri != nil {
		changed["jwks_uri"] = *input.JWKSUri
	}
	if input.SyncOnLogin != nil {
		changed["sync_on_login"] = *input.SyncOnLogin
	}
	if input.AllowLinkConfirmation != nil {
		changed["allow_link_confirmation"] = *input.AllowLinkConfirmation
	}
	if len(input.AttributeMapper) > 0 {
		changed["attribute_mapper_changed"] = true
	}
	if input.Active != nil {
		changed["active"] = *input.Active
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderUpdated, changed)
	}

	pkg.OK(c, gin.H{"provider": p})
}

// DeleteProvider godoc
// @Summary      Delete a federation provider
// @Tags         Admin - Federation
// @Produce      json
// @Param        id path string true "Provider ID"
// @Success      200 {object} map[string]any
// @Failure      400 {object} map[string]any
// @Failure      404 {object} map[string]any
// @Security     BearerAuth
// @Router       /api/v1/admin/federation/{id} [delete]
func (h *Handler) DeleteProvider(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		pkg.HandleError(c, pkg.ErrBadRequest("invalid provider ID"))
		return
	}
	if err := h.service.DeleteProvider(id); err != nil {
		pkg.HandleError(c, err)
		return
	}

	if h.auditService != nil {
		h.auditService.LogFromContext(c, audit.ActionFederationProviderDeleted, map[string]any{
			"provider_id": id,
		})
	}

	pkg.OK(c, gin.H{"message": "provider deleted"})
}
